name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: yarn install

      - name: Run Unit/Integration Tests
        run: yarn nx affected -t test --output-style=stream

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run E2E Tests
        run: yarn nx affected -t e2e  --update-snapshots --output-style=stream

      - name: Fail if snapshots were updated
        id: 'snapshots'
        run: git diff --exit-code

      - name: Create Pull Request with updated snapshots
        if: failure() && steps.snapshots.outcome == 'failure'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: update Playwright snapshots'
          title: 'Update Playwright snapshots'
          body: 'This PR includes updated Playwright snapshots generated from CI.'
          branch: chore/update-playwright-snapshots
          delete-branch: true
          base: ${{ github.head_ref }}
