name: Update Playwright Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests and update snapshots
        run: yarn nx e2e jesse-website --update-snapshots

      - name: Create Pull Request with updated snapshots
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: update Playwright snapshots'
          title: 'Update Playwright snapshots'
          body: 'This PR includes updated Playwright snapshots generated from CI.'
          branch: chore/update-playwright-snapshots
          base: ${{ github.ref_name }}
